# Generated by Django 5.2.1 on 2025-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_phone_number_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('mutual', 'Mutual Followers Only')], default='everyone', max_length=20),
        ),
    ]
